# Generated by Django 4.1.4 on 2023-05-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='uid',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
