# Generated by Django 4.1.4 on 2023-05-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_shop_alter_products_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='uid',
            new_name='pid',
        ),
    ]
